// flow-typed signature: fc663a94cbeb211ab35dd6e235d72bfc
// flow-typed version: <<STUB>>/@n8tb1t/use-scroll-position_v2.0.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@n8tb1t/use-scroll-position'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@n8tb1t/use-scroll-position' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@n8tb1t/use-scroll-position/examples/navbar/gatsby-config' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/gatsby-node' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/src/components/fake-data' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/src/components/nav-links' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/navbar' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/position' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/sidebar' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/examples/navbar/src/styles' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/lib' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/lib/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module '@n8tb1t/use-scroll-position/lib/useScrollPosition' {
  declare module.exports: any;
}

// Filename aliases
declare module '@n8tb1t/use-scroll-position/examples/navbar/gatsby-config.js' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/gatsby-config'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/gatsby-node.js' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/gatsby-node'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/components/fake-data.jsx' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/components/fake-data'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/components/nav-links.jsx' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/components/nav-links'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/index' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/pages'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/index.jsx' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/pages'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/navbar.jsx' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/pages/navbar'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/position.jsx' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/pages/position'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/pages/sidebar.jsx' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/pages/sidebar'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/styles/index' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/styles'
  >;
}
declare module '@n8tb1t/use-scroll-position/examples/navbar/src/styles/index.jsx' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/examples/navbar/src/styles'
  >;
}
declare module '@n8tb1t/use-scroll-position/lib/index' {
  declare module.exports: $Exports<'@n8tb1t/use-scroll-position/lib'>;
}
declare module '@n8tb1t/use-scroll-position/lib/index.js' {
  declare module.exports: $Exports<'@n8tb1t/use-scroll-position/lib'>;
}
declare module '@n8tb1t/use-scroll-position/lib/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/lib/useIsomorphicLayoutEffect'
  >;
}
declare module '@n8tb1t/use-scroll-position/lib/useScrollPosition.js' {
  declare module.exports: $Exports<
    '@n8tb1t/use-scroll-position/lib/useScrollPosition'
  >;
}
