// flow-typed signature: 8f4910a2cc6a4d14287b8671e1ddd82b
// flow-typed version: <<STUB>>/3d-react-carousal_v3.1.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '3d-react-carousal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '3d-react-carousal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '3d-react-carousal/dist' {
  declare module.exports: any;
}

declare module '3d-react-carousal/src' {
  declare module.exports: any;
}

declare module '3d-react-carousal/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '3d-react-carousal/dist/index' {
  declare module.exports: $Exports<'3d-react-carousal/dist'>;
}
declare module '3d-react-carousal/dist/index.js' {
  declare module.exports: $Exports<'3d-react-carousal/dist'>;
}
declare module '3d-react-carousal/src/index' {
  declare module.exports: $Exports<'3d-react-carousal/src'>;
}
declare module '3d-react-carousal/src/index.js' {
  declare module.exports: $Exports<'3d-react-carousal/src'>;
}
declare module '3d-react-carousal/webpack.config.js' {
  declare module.exports: $Exports<'3d-react-carousal/webpack.config'>;
}
