// flow-typed signature: a7b6d8add10d1fdc84af6f9e2b0b2e1c
// flow-typed version: <<STUB>>/react-multivalue-text-input_v0.6.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-multivalue-text-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-multivalue-text-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-multivalue-text-input/build/components/MultipleValueTextInput' {
  declare module.exports: any;
}

declare module 'react-multivalue-text-input/build/components/MultipleValueTextInputItem' {
  declare module.exports: any;
}

declare module 'react-multivalue-text-input/build' {
  declare module.exports: any;
}

declare module 'react-multivalue-text-input/src/components/MultipleValueTextInput' {
  declare module.exports: any;
}

declare module 'react-multivalue-text-input/src/components/MultipleValueTextInputItem' {
  declare module.exports: any;
}

declare module 'react-multivalue-text-input/src' {
  declare module.exports: any;
}

declare module 'react-multivalue-text-input/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-multivalue-text-input/build/components/MultipleValueTextInput.js' {
  declare module.exports: $Exports<'react-multivalue-text-input/build/components/MultipleValueTextInput'>;
}
declare module 'react-multivalue-text-input/build/components/MultipleValueTextInputItem.js' {
  declare module.exports: $Exports<'react-multivalue-text-input/build/components/MultipleValueTextInputItem'>;
}
declare module 'react-multivalue-text-input/build/index' {
  declare module.exports: $Exports<'react-multivalue-text-input/build'>;
}
declare module 'react-multivalue-text-input/build/index.js' {
  declare module.exports: $Exports<'react-multivalue-text-input/build'>;
}
declare module 'react-multivalue-text-input/src/components/MultipleValueTextInput.js' {
  declare module.exports: $Exports<'react-multivalue-text-input/src/components/MultipleValueTextInput'>;
}
declare module 'react-multivalue-text-input/src/components/MultipleValueTextInputItem.js' {
  declare module.exports: $Exports<'react-multivalue-text-input/src/components/MultipleValueTextInputItem'>;
}
declare module 'react-multivalue-text-input/src/index' {
  declare module.exports: $Exports<'react-multivalue-text-input/src'>;
}
declare module 'react-multivalue-text-input/src/index.js' {
  declare module.exports: $Exports<'react-multivalue-text-input/src'>;
}
declare module 'react-multivalue-text-input/webpack.config.js' {
  declare module.exports: $Exports<'react-multivalue-text-input/webpack.config'>;
}
