// flow-typed signature: 62d7877db16dcbf950dbabc429e87a11
// flow-typed version: <<STUB>>/react-use-audio-player_v1.2.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-use-audio-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-use-audio-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-use-audio-player/dist' {
  declare module.exports: any;
}

declare module 'react-use-audio-player/dist/react-use-audio-player.cjs.development' {
  declare module.exports: any;
}

declare module 'react-use-audio-player/dist/react-use-audio-player.cjs.production.min' {
  declare module.exports: any;
}

declare module 'react-use-audio-player/dist/react-use-audio-player.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-use-audio-player/dist/index' {
  declare module.exports: $Exports<'react-use-audio-player/dist'>;
}
declare module 'react-use-audio-player/dist/index.js' {
  declare module.exports: $Exports<'react-use-audio-player/dist'>;
}
declare module 'react-use-audio-player/dist/react-use-audio-player.cjs.development.js' {
  declare module.exports: $Exports<'react-use-audio-player/dist/react-use-audio-player.cjs.development'>;
}
declare module 'react-use-audio-player/dist/react-use-audio-player.cjs.production.min.js' {
  declare module.exports: $Exports<'react-use-audio-player/dist/react-use-audio-player.cjs.production.min'>;
}
declare module 'react-use-audio-player/dist/react-use-audio-player.esm.js' {
  declare module.exports: $Exports<'react-use-audio-player/dist/react-use-audio-player.esm'>;
}
